name: cdq
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - affine=2.3.0=py_0
  - appdirs=1.4.4=pyh9f0ad1d_0
  - appnope=0.1.2=py310hecd8cb5_1001
  - attrs=21.4.0=pyhd8ed1ab_0
  - backcall=0.2.0=py_0
  - beautifulsoup4=4.10.0=pyha770c72_0
  - blosc=1.21.0=he49afe7_0
  - boost-cpp=1.74.0=hdbf7018_7
  - branca=0.4.2=pyhd8ed1ab_0
  - brotli=1.0.9=h0d85af4_6
  - brotli-bin=1.0.9=h0d85af4_6
  - brotlipy=0.7.0=py310he24745e_1003
  - bzip2=1.0.8=h0d85af4_4
  - c-ares=1.18.1=h0d85af4_0
  - ca-certificates=2021.10.8=h033912b_0
  - cairo=1.16.0=he01c77b_1009
  - certifi=2021.10.8=py310h2ec42d9_1
  - cffi=1.15.0=py310hcc37b68_0
  - cfitsio=4.0.0=hb20e66c_0
  - charset-normalizer=2.0.12=pyhd8ed1ab_0
  - click=8.0.4=py310h2ec42d9_0
  - click-plugins=1.1.1=py_0
  - cligj=0.7.2=pyhd8ed1ab_1
  - colorama=0.4.4=pyh9f0ad1d_0
  - contextily=1.2.0=pyhd8ed1ab_0
  - cryptography=36.0.1=py310ha82f1d4_0
  - curl=7.81.0=hf45b732_0
  - cycler=0.11.0=pyhd8ed1ab_0
  - debugpy=1.5.1=py310he9d5cce_0
  - decorator=4.4.2=py_0
  - expat=2.4.6=h96cf925_0
  - fiona=1.8.21=py310h56b70e1_0
  - folium=0.12.1.post1=pyhd8ed1ab_1
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=hab24e00_0
  - fontconfig=2.13.96=h10f422b_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.29.1=py310he24745e_0
  - freetype=2.10.4=h4cff582_1
  - freexl=1.0.6=h0d85af4_0
  - geographiclib=1.52=pyhd8ed1ab_0
  - geopandas=0.10.2=pyhd8ed1ab_1
  - geopandas-base=0.10.2=pyha770c72_1
  - geopy=2.2.0=pyhd8ed1ab_0
  - geos=3.10.2=he49afe7_0
  - geotiff=1.7.0=h0ca5f94_6
  - gettext=0.19.8.1=hd1a6beb_1008
  - giflib=5.2.1=hbcb3906_2
  - haversine=2.5.1=pyhd8ed1ab_0
  - hdf4=4.2.15=hefd3b78_3
  - hdf5=1.12.1=nompi_h2f0ef1a_103
  - icu=69.1=he49afe7_0
  - idna=3.3=pyhd8ed1ab_0
  - ipykernel=6.4.1=py310hecd8cb5_1
  - ipython=7.29.0=py310h20db666_0
  - ipython_genutils=0.2.0=pyhd3eb1b0_1
  - jbig=2.1=h0d85af4_2003
  - jedi=0.18.1=py310hecd8cb5_1
  - jinja2=3.0.3=pyhd8ed1ab_0
  - joblib=1.1.0=pyhd8ed1ab_0
  - jpeg=9e=h0d85af4_0
  - json-c=0.15=hcb556a6_0
  - jupyter_client=6.1.7=py_0
  - jupyter_core=4.9.1=py310hecd8cb5_0
  - kealib=1.4.14=ha22a8b1_3
  - kiwisolver=1.3.2=py310h2fea185_1
  - krb5=1.19.2=hcfbf3a7_3
  - lcms2=2.12=h577c468_0
  - lerc=3.0=he49afe7_0
  - libblas=3.9.0=13_osx64_openblas
  - libbrotlicommon=1.0.9=h0d85af4_6
  - libbrotlidec=1.0.9=h0d85af4_6
  - libbrotlienc=1.0.9=h0d85af4_6
  - libcblas=3.9.0=13_osx64_openblas
  - libcurl=7.81.0=hf45b732_0
  - libcxx=12.0.1=habf9029_1
  - libdap4=3.20.6=h3e144a0_2
  - libdeflate=1.10=h0d85af4_0
  - libedit=3.1.20191231=h0678c8f_2
  - libev=4.33=haf1e3a3_1
  - libffi=3.4.2=h0d85af4_5
  - libgdal=3.4.1=he416c16_4
  - libgfortran=5.0.0=9_3_0_h6c81a4c_23
  - libgfortran5=9.3.0=h6c81a4c_23
  - libglib=2.70.2=hf1fb8c0_4
  - libiconv=1.16=haf1e3a3_0
  - libkml=1.3.0=h8fd9edb_1014
  - liblapack=3.9.0=13_osx64_openblas
  - libnetcdf=4.8.1=nompi_h6609ca0_101
  - libnghttp2=1.47.0=h942079c_0
  - libopenblas=0.3.18=openmp_h3351f45_0
  - libpng=1.6.37=h7cec526_2
  - libpq=14.2=hea3049e_0
  - libpysal=4.6.2=pyhd8ed1ab_0
  - librttopo=1.1.0=hec60dd8_9
  - libsodium=1.0.18=h1de35cc_0
  - libspatialindex=1.9.3=he49afe7_4
  - libspatialite=5.0.1=h88e7940_14
  - libssh2=1.10.0=h52ee1ee_2
  - libtiff=4.3.0=h17f2ce3_3
  - libwebp=1.2.2=h28dabe5_0
  - libwebp-base=1.2.2=h0d85af4_1
  - libxcb=1.13=h0d85af4_1004
  - libxml2=2.9.12=h7e28ab6_1
  - libzip=1.8.0=h8b0c345_1
  - libzlib=1.2.11=h9173be1_1013
  - llvm-openmp=13.0.1=hda6cdc1_0
  - lz4-c=1.9.3=he49afe7_1
  - mapclassify=2.4.3=pyhd8ed1ab_0
  - markupsafe=2.1.0=py310h1961e1f_0
  - matplotlib-base=3.5.1=py310hfc59cd6_0
  - matplotlib-inline=0.1.2=pyhd3eb1b0_2
  - mercantile=1.2.1=pyhd8ed1ab_0
  - momepy=0.5.2=pyhd8ed1ab_0
  - munch=2.5.0=py_0
  - munkres=1.1.4=pyh9f0ad1d_0
  - ncurses=6.3=he49afe7_0
  - networkx=2.6.3=pyhd8ed1ab_1
  - nspr=4.32=hcd9eead_1
  - nss=3.74=h31e2bf1_0
  - numpy=1.22.2=py310hfbbbacf_0
  - openjpeg=2.4.0=h6e7aa92_1
  - openssl=1.1.1n=h6c3fc93_0
  - osmnx=1.1.2=pyhd8ed1ab_0
  - packaging=21.3=pyhd8ed1ab_0
  - pandas=1.4.1=py310hdd25497_0
  - parso=0.8.0=py_0
  - pcre=8.45=he49afe7_0
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pillow=9.0.1=py310h382dc3b_2
  - pip=22.0.3=pyhd8ed1ab_0
  - pixman=0.40.0=hbcb3906_0
  - poppler=22.01.0=h9573804_0
  - poppler-data=0.4.11=hd8ed1ab_0
  - postgresql=14.2=he8fe76e_0
  - proj=8.2.1=h1512c50_0
  - prompt-toolkit=3.0.8=py_0
  - pthread-stubs=0.4=hc929b4f_1001
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pycparser=2.21=pyhd8ed1ab_0
  - pygeos=0.12.0=py310hbb63119_1
  - pygments=2.7.1=py_0
  - pyopenssl=22.0.0=pyhd8ed1ab_0
  - pyparsing=3.0.7=pyhd8ed1ab_0
  - pyproj=3.3.0=py310h4ed7dbf_1
  - pysocks=1.7.1=py310h2ec42d9_4
  - python=3.10.2=h1dd9edd_3_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python_abi=3.10=2_cp310
  - pytz=2021.3=pyhd8ed1ab_0
  - pyzmq=22.3.0=py310he9d5cce_2
  - rasterio=1.2.10=py310h4193d74_4
  - readline=8.1=h05e3726_0
  - requests=2.27.1=pyhd8ed1ab_0
  - rtree=0.9.7=py310had9ce37_3
  - scikit-learn=1.0.2=py310h598de7d_0
  - scipy=1.8.0=py310h47774c9_1
  - setuptools=60.9.3=py310h2ec42d9_0
  - shapely=1.8.0=py310hbb63119_5
  - six=1.16.0=pyh6c4a22f_0
  - snuggs=1.4.7=py_0
  - soupsieve=2.3.1=pyhd8ed1ab_0
  - sqlite=3.37.0=h23a322b_0
  - threadpoolctl=3.1.0=pyh8a188c0_0
  - tiledb=2.6.2=hca4410a_1
  - tk=8.6.12=h5dbffcc_0
  - tornado=6.1=py310hca72f7f_0
  - tqdm=4.63.0=pyhd8ed1ab_0
  - traitlets=5.0.5=py_0
  - tzcode=2021e=h0d85af4_0
  - tzdata=2021e=he74cb21_0
  - unicodedata2=14.0.0=py310he24745e_0
  - urllib3=1.26.8=pyhd8ed1ab_1
  - wcwidth=0.2.5=py_0
  - wheel=0.37.1=pyhd8ed1ab_0
  - xerces-c=3.2.3=h6564042_4
  - xorg-libxau=1.0.9=h35c211d_0
  - xorg-libxdmcp=1.1.3=h35c211d_0
  - xyzservices=2022.2.0=pyhd8ed1ab_0
  - xz=5.2.5=haf1e3a3_1
  - yaml=0.2.5=haf1e3a3_0
  - zeromq=4.3.4=h23ab428_0
  - zlib=1.2.11=h9173be1_1013
  - zstd=1.5.2=h582d3a0_0
  - pip:
    - gdal==3.4.1
    - pyyaml==6.0
prefix: /opt/miniconda3/envs/cdq
